# Generated by Django 3.0 on 2020-11-15 14:56

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 11, 15, 14, 56, 24, 856827), null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
